const clean = v => String(v ?? '').trim();
const esc = v => String(v ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const text = v => Array.isArray(v) ? v.join('\n') : (typeof v === 'object' && v !== null ? JSON.stringify(v, null, 2) : String(v ?? ''));
export function buildProfessionalReportModel(input={}) {
  const c=input.child||{}, a=input.assessment||{};
  const sections=input.sections||[];
  return {meta:{report_id:clean(input.report_id),report_version:clean(input.report_version||'AUTIBLOOM-REPORT-V1'),generated_at:new Date().toISOString()},child:{name:clean(c.name),date_of_birth:clean(c.date_of_birth)},assessment:{title:clean(a.title||'AUTIBLOOM Sensory Profile Clinical Report'),date:clean(a.date),assessor:clean(a.assessor)},sections:sections.filter(s=>clean(s.body)),disclaimer:'This report is a structured screening/clinical-review summary, not a diagnosis. Final interpretation remains the responsibility of the qualified clinician.'};
}
export function renderProfessionalReportHtml(model) {
  const sections=model.sections.map(s=>`<section><h2>${esc(s.title)}</h2>${text(s.body).split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}</section>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AUTIBLOOM Clinical Report</title><style>@page{size:A4;margin:18mm 16mm}body{font-family:Arial,Helvetica,sans-serif;color:#172033;line-height:1.55;margin:0}.header{border-bottom:2px solid #172033;padding-bottom:12px;margin-bottom:20px}.brand{font-size:25px;font-weight:800}.sub{color:#64748b;font-size:12px}h1{font-size:22px}h2{font-size:16px;margin-bottom:6px}section{page-break-inside:avoid;margin:22px 0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:12px}.disclaimer{background:#f4f6f9;padding:10px;border-radius:8px;font-size:11px}.footer{border-top:1px solid #d9dee8;margin-top:24px;padding-top:10px;font-size:10px;color:#64748b}</style></head><body><header class="header"><div class="brand">AUTIBLOOM</div><div class="sub">Clinical Assessment Report</div></header><h1>${esc(model.assessment.title)}</h1><div class="meta"><div><b>Child:</b> ${esc(model.child.name)}</div><div><b>Date of Birth:</b> ${esc(model.child.date_of_birth)}</div><div><b>Assessment Date:</b> ${esc(model.assessment.date)}</div><div><b>Assessor:</b> ${esc(model.assessment.assessor)}</div></div>${sections}<section><h2>Important Information</h2><div class="disclaimer">${esc(model.disclaimer)}</div></section><footer class="footer">AUTIBLOOM · ${esc(model.meta.report_version)}</footer></body></html>`;
}
